### ISSUE TITLE
Exception with Unity 5 in AddExtension

### ISSUE THREAD

**Issue by Loiti78** [roblevine/UnityLog4NetExtension#9]
Hi,

i get a method not found exception during call of
Container.AddNewExtension<Log4NetExtension>();

Please Help

Methode nicht gefunden: "Unity.Strategy.IStagedStrategyChain`1<Unity.Builder.UnityBuildStage> Unity.Extension.ExtensionContext.get_Strategies()".

   bei UnityLog4NetExtension.Log4Net.Log4NetExtension.Initialize()
   bei Unity.Extension.UnityContainerExtension.InitializeExtension(ExtensionContext context) in C:\projects\unity\Abstractions\src\Extension\UnityContainerExtension.cs:Zeile 29.
   bei Unity.UnityContainer.AddExtension(UnityContainerExtension extension) in C:\projects\unity\Container\src\UnityContainer.cs:Zeile 248.
   bei Unity.UnityContainerExtensions.AddNewExtension[TExtension](IUnityContainer container) in C:\projects\unity\Abstractions\src\Utility\UnityContainerExtensions.cs:Zeile 770.

**Comment by roblevine** [comment]
Thanks for getting back to me.

Let me have a closer look...

**Comment by roblevine** [comment]
Can you check exactly which version of Unity you are using, and which version of the extension?

**Comment by roblevine** [comment]
(it looks like the latest version of my extension (5.0.0.0) hasn't finished validating on NuGet yet, so I suspect you're on the old version. Sorry - I called it too soon!.

**Comment by Loiti78** [comment]
I downloaded the extension and set the referenece manually it is 5.0.0.0
Unity is 5.4.0

**Comment by roblevine** [comment]
It should now be fixed - there was a problem with the delay-signing step which I've now removed.
v5.0.1 should work - please let me know. Sorry for the broken release!

**Comment by Loiti78** [comment]
I tried the new version 5.0.1.0 of the extension, i am still getting the same error...

**Comment by roblevine** [comment]
I'm struggling to recreate this issue now. Downloading the .dll from the v5.0.1 release and using tis works on my test applications.
Is it still exactly the same exception, at AddExtension time?
Also - can you double-check you're removed all references to the previous version and also do a complete clean and rebuild.
The exception you report was exactly what I saw too, but for me it is now resolved.

Thanks,

**Comment by Loiti78** [comment]
still the same error.

the exact call is: Container.AddNewExtension<Log4NetExtension>();

**Comment by roblevine** [comment]
Can you go into the executing bin directory and get me the exact assembly version numbers of the Unity and Log4Net assemblies? I want to try and recreate with the exact same versions. (Also  can you double check the extension dll number and make sure it is 5.0.1 in the actual executing bin directory).
Also, are there any build warnings relating to versions of anything? 
Thanks

**Comment by roblevine** [comment]
By the way - thank you for taking time out to help debug the issue!

**Comment by Loiti78** [comment]
Ausnahme ausgelöst: "System.MissingMethodException" in Unity.Abstractions.dll
Eine Ausnahme vom Typ "System.MissingMethodException" ist in Unity.Abstractions.dll aufgetreten, doch wurde diese im Benutzercode nicht verarbeitet.
Methode nicht gefunden: "Unity.Strategy.IStagedStrategyChain`1<Unity.Builder.UnityBuildStage> Unity.Extension.ExtensionContext.get_Strategies()".

14>      Diese Version wird anstelle der ursprünglichen Version 2.3.1.0 in "C:\Dev\Repos\RapAut\packages\UnityLog4NetExten
14>  sion.5.0.1\lib\net45\UnityLog4NetExtension.dll" verwendet, da AutoUnify auf "true" festgelegt ist.

Unity.Abstractions is 2.4

Do you use Unity.Abstractions version 2.3.1?

**Comment by Loiti78** [comment]
2.4.0.150
@ENikS ENikS released this 2 days ago

Assets
182 KB Unity.Abstractions.2.4.0.nupkg
 Source code (zip)
 Source code (tar.gz)
This Release
This release is primarily addresses extending of strategy chains to support multiple types of strategies. These changes are required to implement custom Property, Method, and Constructor selectors.

Breaking changes
#20 A non generic interface IStagedStrategyChain has been retired. Generic interface IStagedStrategyChain<TStageEnum> has been modified to accept strategy type argument. StagedStrategyChain has been modified to allow different strategy types

**Comment by ENikS** [comment]
v2.4.0 breaks some interfaces. It should have been called v3.0.0

I am working on releasing v3.0.0 with more breaking changes. You could roll back to v2.3.2 meanwhile.

**Comment by roblevine** [comment]
Hi @Loiti78 

Abstractions version: yes - I'm on an older version of Unity.Abstractions. UnityLog4NetExtension was built against the combined single Unity NuGet package 5.0.2 which contains Unity.Abstractions to 2.3.1 and Unity.Container 5.3.2.
 
Have you tried downgrading Unity.Abstractions to 2.3.1 as suggested by @ENikS? 

I'll also rebuild and create a release package against Unity 5.5.0 which was released a few days ago.

Thanks

**Comment by bleh5** [comment]
Hi @roblevine  I'm using unity 5.5.4 and UnityLog4NetExtension 5.0.1 and getting an error when I run my web api "Method not found: 'Unity.Strategy.IStagedStrategyChain`..." on 

```
unityContainer = new UnityContainer();
unityContainer.AddNewExtension<Log4NetExtension>();
```
Am I missing something or is there a bug in this build?

**Comment by bleh5** [comment]
I was actually able to make it work by going to unity 4 and unitylog4netextension 2 but I'm still having an issue to link the extension to my wrapper log class

**Comment by zhoqa** [comment]
Hi @roblevine,

You wrote
> I'll also rebuild and create a release package against Unity 5.5.0 which was released a few days ago.

Could you tell us when are you going to do it? ;) Currently the users of unitylog4netextension are stick to Unity version 5.3.2 as upgrading the Unity package to any later version leads to exception in
`unityContainer.AddNewExtension<Log4NetExtension>();`

**Comment by bleh5** [comment]
Hi @zhoqa  
So now I can use Unity 5.3.2 with the latest unitylog4netextension ? Because last time I had to use Unity 4 with unitylog4netextension 2

**Comment by zhoqa** [comment]
Hi @HadiNass

**Comment by zhoqa** [comment]
Hi @HadiNass.
Oops... Sorry, maybe I was wrong. I noticed that I use not the original unitylog4netextension nuget package, but a few source files from it, most likely with some my own little corrections. I need to check if I'm able to use the original unitylog4netextension nuget package. I can't check it right now, will tell you later.

**Comment by zhoqa** [comment]
Hi @HadiNass,

**Comment by zhoqa** [comment]
Hi @HadiNass.
I found that in another project I use Unity.5.3.2 + UnityLog4NetExtension.5.0.1 and it seems to work fine. So you may try it, too.

**Comment by HadiNass** [comment]
Hi @zhoqa  it's causing a problem with Unity Abstraction on 
```
public static DIContainer Container
        {
            get
            {
                if (container == null)
                    container = new DIContainer();//problem here
                return container;
            }
        }
```
'Could not load file or assembly 'Unity.Abstractions, Version=3.1.1.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f' or one of its dependencies. The system cannot find the file specified.'

FileNotFoundException: Could not load file or assembly 'Unity.Abstractions, Version=2.3.1.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f' or one of its dependencies. The system cannot find the file specified.

**Comment by HadiNass** [comment]
Which version of Unity.Abstraction works with unity 5.3.2 + UnityLog4NetExtension.5.0.1 ?

**Comment by zhoqa** [comment]
Hi @HadiNass.

I use Unity.Abstraction included into Unity 5.3.2 nuget package. Maybe I'm just lucky to avoid the problematic line as my container is not null. I initialize my container like this:
```
public class CommonServiceLocatorAdapter : ServiceLocatorImplBase
{
    private IUnityContainer container;

    public CommonServiceLocatorAdapter(IUnityContainer container)
    {
        this.container = container;
    }

    protected override object DoGetInstance(Type serviceType, string key)
    {
        return container.Resolve(serviceType, key);
    }

    protected override IEnumerable<object> DoGetAllInstances(Type serviceType)
    {
        return container.ResolveAll(serviceType);
    }
}
```
then
```
class Bootstrapper
{
    private IUnityContainer Container { get; } = new UnityContainer();
    ...
}
```
then
```
using CommonServiceLocator;
...
ServiceLocator.SetLocatorProvider(() => new CommonServiceLocatorAdapter(Container));
```

**Comment by HadiNass** [comment]
Hi @zhoqa it's fine I went back to Unity 4 but I'm still having an issue I was hopping you can help me with if you can, I'm using a wrapper logger 
```
    public class MyLog4NetLogger : ILogger
    {
        private readonly ILog _logger;

        public MyLog4NetLogger(ILog logger)
        {
            _logger = logger;
        }
   }
```
And I'm using the 
`unityContainer.AddNewExtension<Log4NetExtension>();`

My problem is that in the log I get the method name of the wrapper (`Utilities.Logger.MyLog4NetLogger`) instead of the method itself! Any clue how to solve this?

**Comment by zhoqa** [comment]
Hi @HadiNass.
If I can't use log4net with Unity I just use an old regular approach:
`private static ILog Logger { get; } = LogManager.GetLogger(typeof(MyLog4NetLogger));`

**Comment by HadiNass** [comment]
Hi @zhoqa  

But Unity is working with log4net, the only problem is the method name when logging, this way im calling implicitly only once the logger instead of calling one in every class

**Comment by zhoqa** [comment]
Hi @HadiNass 
Sorry, my previous comment was irrelevant. Please check the link, maybe it can help (but I'm not sure).
https://stackoverflow.com/questions/157232/how-to-log-methodname-when-wrapping-log4net

**Comment by jonathh21** [comment]
FWIW - I have just done this same dance between Unity, Log4NetExtensions and UnityAbstractions.. I didn't roll back to an earlier version but I did fully remove and re-add everything to ensure it was nothing screwy..

Currently it is NOT working for me :(

Method not found: 'Unity.Strategy.IStagedStrategyChain`1<Unity.Builder.UnityBuildStage> Unity.Extension.ExtensionContext.get_Strategies()'.

**Comment by zhoqa** [comment]
Hi @HadiNass, @jonathh21,

**Comment by zhoqa** [comment]
Hi @jonathh21 , @HadiNass ,
Attached please find a working solution (VS 15.5.2).
[ConsoleApp1.zip](https://github.com/roblevine/UnityLog4NetExtension/files/1620282/ConsoleApp1.zip)
Note that it will stop working if you upgrade the Unity package >5.3.2.

**Comment by roblevine** [comment]
Hi all,

Apologies for my delay in replying.

There is an issue here as soon as the abstractions library is above 2.3. Internally, quite a lot has changed in this release (despite it only being a minor version increment which should be backward compatible) and this breaks the extension. Unfortunately, v2.4 is what ships with Unity >5.3.2 hence the problems.

I've had a bit of a look and the extension will need a little re-work but I haven't been able to make time to understand how the new version of Unity requires you to register policies. I'm hoping to find time this weekend.

Thanks for your patience,

Rob

**Comment by ENikS** [comment]
You could try [this package](https://www.nuget.org/packages/Unity.log4net/)

**Comment by roblevine** [comment]
Hi Eugene,

It sounds like this now supercedes the functionality in
UnityLog4NetExtension for Unity 5?

Is there still any point maintaining this one? We briefly discussed passing
this o email over to the Unity project. Is that still worthwhile or should
I retire this?

Kind Regards,


Rob

**Comment by ENikS** [comment]
I think this one could be safely retired. The new package should be used for Unity.5+

**Comment by roblevine** [comment]
Is it worth you taking this one and replacing the code? That way it will be
in the same NuGet package as the current extension and people will get the
automatic upgrade?

If you'd rather start clean, I'm happy to retire this one.

Thanks,

Rob

**Comment by ENikS** [comment]
I already started clean. I'd rather everyone just linking to a new package so it is easier to maintain.

**Comment by zhoqa** [comment]
I started clean.

**Comment by roblevine** [comment]
This extension is now retired for Unity v5 and onward. Please use the [official Unity Log4Net extension](https://github.com/unitycontainer/log4net) instead.

**Comment by roblevine** [comment]
This extension is now retired for Unity v5 and onward. Please use the [official Unity Log4Net extension](https://github.com/unitycontainer/log4net) instead.

**Comment by jonathh21** [comment]
Sad times.

Thanks for all your effort. It was not unnoticed!

**Comment by roblevine** [comment]
Thanks @jonathh21 - that is very much appreciated!

Onward, in search of another interesting open source project.
